/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedConfiguracaoRouteImport } from './routes/_authenticated/configuracao'
import { Route as AuthenticatedCultoRouteImport } from './routes/_authenticated/culto'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedConfiguracaoIndexRouteImport } from './routes/_authenticated/configuracao.index'
import { Route as AuthenticatedConfiguracaoUsuariosRouteImport } from './routes/_authenticated/configuracao.usuarios'
import { Route as AuthenticatedEscalaCultoIdRouteImport } from './routes/_authenticated/escala.$cultoId'
import { Route as AuthenticatedEscalaNovoRouteImport } from './routes/_authenticated/escala.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracaoRoute =
  AuthenticatedConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCultoRoute = AuthenticatedCultoRouteImport.update({
  id: '/culto',
  path: '/culto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracaoIndexRoute =
  AuthenticatedConfiguracaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracaoRoute,
  } as any)
const AuthenticatedConfiguracaoUsuariosRoute =
  AuthenticatedConfiguracaoUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracaoRoute,
  } as any)
const AuthenticatedEscalaCultoIdRoute =
  AuthenticatedEscalaCultoIdRouteImport.update({
    id: '/$cultoId',
    path: '/$cultoId',
    getParentRoute: () => AuthenticatedEscalaRoute,
  } as any)
const AuthenticatedEscalaNovoRoute = AuthenticatedEscalaNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedEscalaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracao': typeof AuthenticatedConfiguracaoRouteWithChildren
  '/culto': typeof AuthenticatedCultoRoute
  '/escala': typeof AuthenticatedEscalaRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/configuracao/usuarios': typeof AuthenticatedConfiguracaoUsuariosRoute
  '/escala/$cultoId': typeof AuthenticatedEscalaCultoIdRoute
  '/escala/novo': typeof AuthenticatedEscalaNovoRoute
  '/configuracao/': typeof AuthenticatedConfiguracaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/culto': typeof AuthenticatedCultoRoute
  '/escala': typeof AuthenticatedEscalaRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
  '/configuracao/usuarios': typeof AuthenticatedConfiguracaoUsuariosRoute
  '/escala/$cultoId': typeof AuthenticatedEscalaCultoIdRoute
  '/escala/novo': typeof AuthenticatedEscalaNovoRoute
  '/configuracao': typeof AuthenticatedConfiguracaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/configuracao': typeof AuthenticatedConfiguracaoRouteWithChildren
  '/_authenticated/culto': typeof AuthenticatedCultoRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
  '/_authenticated/configuracao/usuarios': typeof AuthenticatedConfiguracaoUsuariosRoute
  '/_authenticated/escala/$cultoId': typeof AuthenticatedEscalaCultoIdRoute
  '/_authenticated/escala/novo': typeof AuthenticatedEscalaNovoRoute
  '/_authenticated/configuracao/': typeof AuthenticatedConfiguracaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/configuracao'
    | '/culto'
    | '/escala'
    | '/perfil'
    | '/repertorio'
    | '/configuracao/usuarios'
    | '/escala/$cultoId'
    | '/escala/novo'
    | '/configuracao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/culto'
    | '/escala'
    | '/perfil'
    | '/repertorio'
    | '/configuracao/usuarios'
    | '/escala/$cultoId'
    | '/escala/novo'
    | '/configuracao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/configuracao'
    | '/_authenticated/culto'
    | '/_authenticated/escala'
    | '/_authenticated/perfil'
    | '/_authenticated/repertorio'
    | '/_authenticated/configuracao/usuarios'
    | '/_authenticated/escala/$cultoId'
    | '/_authenticated/escala/novo'
    | '/_authenticated/configuracao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracao': {
      id: '/_authenticated/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof AuthenticatedConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/culto': {
      id: '/_authenticated/culto'
      path: '/culto'
      fullPath: '/culto'
      preLoaderRoute: typeof AuthenticatedCultoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracao/': {
      id: '/_authenticated/configuracao/'
      path: '/'
      fullPath: '/configuracao/'
      preLoaderRoute: typeof AuthenticatedConfiguracaoIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracaoRoute
    }
    '/_authenticated/configuracao/usuarios': {
      id: '/_authenticated/configuracao/usuarios'
      path: '/usuarios'
      fullPath: '/configuracao/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracaoUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracaoRoute
    }
    '/_authenticated/escala/$cultoId': {
      id: '/_authenticated/escala/$cultoId'
      path: '/$cultoId'
      fullPath: '/escala/$cultoId'
      preLoaderRoute: typeof AuthenticatedEscalaCultoIdRouteImport
      parentRoute: typeof AuthenticatedEscalaRoute
    }
    '/_authenticated/escala/novo': {
      id: '/_authenticated/escala/novo'
      path: '/novo'
      fullPath: '/escala/novo'
      preLoaderRoute: typeof AuthenticatedEscalaNovoRouteImport
      parentRoute: typeof AuthenticatedEscalaRoute
    }
  }
}

interface AuthenticatedConfiguracaoRouteChildren {
  AuthenticatedConfiguracaoUsuariosRoute: typeof AuthenticatedConfiguracaoUsuariosRoute
  AuthenticatedConfiguracaoIndexRoute: typeof AuthenticatedConfiguracaoIndexRoute
}

const AuthenticatedConfiguracaoRouteChildren: AuthenticatedConfiguracaoRouteChildren =
  {
    AuthenticatedConfiguracaoUsuariosRoute:
      AuthenticatedConfiguracaoUsuariosRoute,
    AuthenticatedConfiguracaoIndexRoute: AuthenticatedConfiguracaoIndexRoute,
  }

const AuthenticatedConfiguracaoRouteWithChildren =
  AuthenticatedConfiguracaoRoute._addFileChildren(
    AuthenticatedConfiguracaoRouteChildren,
  )

interface AuthenticatedEscalaRouteChildren {
  AuthenticatedEscalaCultoIdRoute: typeof AuthenticatedEscalaCultoIdRoute
  AuthenticatedEscalaNovoRoute: typeof AuthenticatedEscalaNovoRoute
}

const AuthenticatedEscalaRouteChildren: AuthenticatedEscalaRouteChildren = {
  AuthenticatedEscalaCultoIdRoute: AuthenticatedEscalaCultoIdRoute,
  AuthenticatedEscalaNovoRoute: AuthenticatedEscalaNovoRoute,
}

const AuthenticatedEscalaRouteWithChildren =
  AuthenticatedEscalaRoute._addFileChildren(AuthenticatedEscalaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracaoRoute: typeof AuthenticatedConfiguracaoRouteWithChildren
  AuthenticatedCultoRoute: typeof AuthenticatedCultoRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracaoRoute: AuthenticatedConfiguracaoRouteWithChildren,
  AuthenticatedCultoRoute: AuthenticatedCultoRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
